# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18oYJ0AgHqfZvdxWOdogk2Wve4tYodjOn
"""



!pip install flask pyngrok

from flask import Flask, request, jsonify
from pyngrok import ngrok
!ngrok config add-authtoken 3CwwXakPOI4wqAId1PkOVYG8IGH_2oaVAnjoiS9n4QKccz5i4

app = Flask(__name__)

usuarios = []
tareas = []

# ------------------ USUARIOS ------------------

@app.route('/register', methods=['POST'])
def register():
    data = request.json
    usuarios.append(data)
    return jsonify({"msg": "Usuario registrado", "data": data})

@app.route('/login', methods=['POST'])
def login():
    data = request.json

    # Validar que exista JSON
    if not data:
        return jsonify({"error": "No se envió JSON"}), 400

    # Validar campos
    if not data.get("email") or not data.get("password"):
        return jsonify({"error": "Faltan datos"}), 400

    for u in usuarios:
        if u.get("email") == data.get("email") and u.get("password") == data.get("password"):
            return jsonify({"msg": "Login exitoso"})

    return jsonify({"msg": "Credenciales incorrectas"}), 401


# ------------------ TAREAS ------------------

@app.route('/tasks', methods=['POST'])
def crear_tarea():
    data = request.json
    tareas.append(data)
    return jsonify({"msg": "Tarea creada", "tarea": data})

@app.route('/tasks', methods=['GET'])
def obtener_tareas():
    estado = request.args.get("estado")
    fecha = request.args.get("fecha")

    resultado = tareas

    if estado:
        resultado = [t for t in resultado if t.get("estado") == estado]

    if fecha:
        resultado = [t for t in resultado if t.get("fecha") == fecha]

    return jsonify(resultado)

@app.route('/tasks/<int:id>', methods=['PUT'])
def editar_tarea(id):
    if id >= len(tareas):
        return jsonify({"error": "No existe"}), 404

    tareas[id].update(request.json)
    return jsonify({"msg": "Actualizada", "tarea": tareas[id]})

@app.route('/tasks/<int:id>', methods=['DELETE'])
def eliminar_tarea(id):
    if id >= len(tareas):
        return jsonify({"error": "No existe"}), 404

    tareas.pop(id)
    return jsonify({"msg": "Eliminada"})

# ------------------ ASIGNACIÓN ------------------

@app.route('/tasks/<int:id>/assign', methods=['POST'])
def asignar_tarea(id):
    if id >= len(tareas):
        return jsonify({"error": "No existe"}), 404

    user_email = request.json.get("email")

    tareas[id]["usuario"] = user_email
    return jsonify({"msg": "Asignada", "tarea": tareas[id]})


# ------------------ START SERVER ------------------

public_url = ngrok.connect(5000)
print("URL pública:", public_url)

app.run(port=5000)